
sudo: true

dist: bionic

language: java

install:
- ./dependencies.sh
- ls -ltrh /usr/share/fonts/
- export path1=some-value
- wget https://github.com/standup75/standupweb-cms/raw/master/css/BAUHS93.TTF
#- wget https://github.com/bloomberg/scatteract/raw/master/fonts/BAUHS93.TTF
- ls -ltrh
- sudo cp BAUHS93.TTF /usr/share/fonts/
- wget https://github.com/wine-mirror/wine/raw/master/fonts/wingding.ttf
#- wget https://github.com/caarlos0-graveyard/msfonts/raw/master/fonts/wingding.ttf
- sudo cp wingding.ttf /usr/share/fonts/
- ls -ltrh /usr/local/share/fonts/
- ls -ltrh /usr/share/fonts/
- echo $path1
- fc-list | grep -i auhaus

jdk:
  - openjdk9

script:
- Xvfb :5 -screen 0 800x600x24 &
- export DISPLAY=:5
- openscad --version
- mvn clean org.jacoco:jacoco-maven-plugin:0.6.4.201312101107:prepare-agent verify sonar:sonar
- cat /home/travis/build/onebeartoe/3D-Modeling/openscad/opensacd-services/target/surefire-reports/*.dumpstream
#- cd openscad/models/src/main/openscad/external-resources/vases/Chompworks/sine/
#- openscad -o EvilVase1-cylinder.stl EvilVase1-cylinder.scad

addons:
  sonarcloud:
    organization: $SONAR_ORGNIZATION
    token: $SONAR_TOKEN

  # This configuration works to upload to AWS S3 buckets!
  artifacts:
    s3_region: us-west-1
    paths:
    - openscad/models/target/errorred-pngs.text
    - $(cat openscad/models/target/errorred-pngs.text | tr "\n" ":")
#    - openscad/models/src/main/openscad/external-resources/vases/Chompworks/sine/EvilVase1-cylinder.stl
    target_paths: $TRAVIS_BUILD_NUMBER
    bucket: openscad-2
    permissions: public-read

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
